#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

# build Apache Thrift on Travis CI - https://travis-ci.org/

language: generic

env:
  global:
    - CMAKE_GENERATOR="Unix Makefiles" CMAKE_OPTIONS="-DBUILD_COMPILER=ON -DBUILD_LIBRARIES=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF" 

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux-x64"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_PLATFORM="Darwin-x64"

install:
  - build/paul/1-install-deps.sh
  - export PATH="/data/bin:/usr/local/opt/bison/bin:$PATH" # bison is just for osx

script:
  - CMAKE_BUILD_TYPE=Debug build/paul/2-build.sh
  - CMAKE_BUILD_TYPE=Release build/paul/2-build.sh

after_success:
  - CMAKE_BUILD_TYPE=Debug build/paul/3-release.sh
  - CMAKE_BUILD_TYPE=Release build/paul/3-release.sh


